// S&P 500 Ticker Symbols with Company Names (Updated: 2025-06-10)
// Total: 504 stocks (includes companies with multiple share classes, and COIN)

const SP500_COMPANIES = [
  { symbol: "MMM", name: "3M Company" },
  { symbol: "AOS", name: "A.O. Smith Corporation" },
  { symbol: "ABT", name: "Abbott Laboratories" },
  { symbol: "ABBV", name: "AbbVie Inc." },
  { symbol: "ACN", name: "Accenture plc" },
  { symbol: "ADBE", name: "Adobe Inc." },
  { symbol: "AMD", name: "Advanced Micro Devices, Inc." },
  { symbol: "AES", name: "The AES Corporation" },
  { symbol: "AFL", name: "Aflac Incorporated" },
  { symbol: "A", name: "Agilent Technologies, Inc." },
  { symbol: "APD", name: "Air Products and Chemicals, Inc." },
  { symbol: "ABNB", name: "Airbnb, Inc." },
  { symbol: "AKAM", name: "Akamai Technologies, Inc." },
  { symbol: "ALB", name: "Albemarle Corporation" },
  { symbol: "ARE", name: "Alexandria Real Estate Equities, Inc." },
  { symbol: "ALGN", name: "Align Technology, Inc." },
  { symbol: "ALLE", name: "Allegion plc" },
  { symbol: "LNT", name: "Alliant Energy Corporation" },
  { symbol: "ALL", name: "The Allstate Corporation" },
  { symbol: "GOOGL", name: "Alphabet Inc. (Class A)" },
  { symbol: "GOOG", name: "Alphabet Inc. (Class C)" },
  { symbol: "MO", name: "Altria Group, Inc." },
  { symbol: "AMZN", name: "Amazon.com, Inc." },
  { symbol: "AMCR", name: "Amcor plc" },
  { symbol: "AEE", name: "Ameren Corporation" },
  { symbol: "AAL", name: "American Airlines Group Inc." },
  { symbol: "AEP", name: "American Electric Power Company, Inc." },
  { symbol: "AXP", name: "American Express Company" },
  { symbol: "AIG", name: "American International Group, Inc." },
  { symbol: "AMT", name: "American Tower Corporation" },
  { symbol: "AWK", name: "American Water Works Company, Inc." },
  { symbol: "AMP", name: "Ameriprise Financial, Inc." },
  { symbol: "AME", name: "AMETEK, Inc." },
  { symbol: "AMGN", name: "Amgen Inc." },
  { symbol: "APH", name: "Amphenol Corporation" },
  { symbol: "ADI", name: "Analog Devices, Inc." },
  { symbol: "ANSS", name: "ANSYS, Inc." },
  { symbol: "AON", name: "Aon plc" },
  { symbol: "APA", name: "APA Corporation" },
  { symbol: "AAPL", name: "Apple Inc." },
  { symbol: "AMAT", name: "Applied Materials, Inc." },
  { symbol: "APTV", name: "Aptiv PLC" },
  { symbol: "ACGL", name: "Arch Capital Group Ltd." },
  { symbol: "ADM", name: "Archer-Daniels-Midland Company" },
  { symbol: "ANET", name: "Arista Networks, Inc." },
  { symbol: "AJG", name: "Arthur J. Gallagher & Co." },
  { symbol: "AIZ", name: "Assurant, Inc." },
  { symbol: "T", name: "AT&T Inc." },
  { symbol: "ATO", name: "Atmos Energy Corporation" },
  { symbol: "ADSK", name: "Autodesk, Inc." },
  { symbol: "ADP", name: "Automatic Data Processing, Inc." },
  { symbol: "AZO", name: "AutoZone, Inc." },
  { symbol: "AVB", name: "AvalonBay Communities, Inc." },
  { symbol: "AVY", name: "Avery Dennison Corporation" },
  { symbol: "AXON", name: "Axon Enterprise, Inc." },
  { symbol: "BKR", name: "Baker Hughes Company" },
  { symbol: "BALL", name: "Ball Corporation" },
  { symbol: "BAC", name: "Bank of America Corporation" },
  { symbol: "BK", name: "The Bank of New York Mellon Corporation" },
  { symbol: "BBWI", name: "Bath & Body Works, Inc." },
  { symbol: "BAX", name: "Baxter International Inc." },
  { symbol: "BDX", name: "Becton, Dickinson and Company" },
  { symbol: "BRK.A", name: "Berkshire Hathaway Inc. (Class A)" },
  { symbol: "BRK.B", name: "Berkshire Hathaway Inc. (Class B)" },
  { symbol: "BBY", name: "Best Buy Co., Inc." },
  { symbol: "BIO", name: "Bio-Rad Laboratories, Inc." },
  { symbol: "TECH", name: "Bio-Techne Corporation" },
  { symbol: "BIIB", name: "Biogen Inc." },
  { symbol: "BLK", name: "BlackRock, Inc." },
  { symbol: "BX", name: "Blackstone Inc." },
  { symbol: "BA", name: "The Boeing Company" },
  { symbol: "BKNG", name: "Booking Holdings Inc." },
  { symbol: "BWA", name: "BorgWarner Inc." },
  { symbol: "BSX", name: "Boston Scientific Corporation" },
  { symbol: "BMY", name: "Bristol-Myers Squibb Company" },
  { symbol: "AVGO", name: "Broadcom Inc." },
  { symbol: "BR", name: "Broadridge Financial Solutions, Inc." },
  { symbol: "BRO", name: "Brown & Brown, Inc." },
  { symbol: "BF.B", name: "Brown-Forman Corporation (Class B)" },
  { symbol: "BLDR", name: "Builders FirstSource, Inc." },
  { symbol: "BG", name: "Bunge Limited" },
  { symbol: "BXP", name: "BXP, Inc." },
  { symbol: "CHRW", name: "C.H. Robinson Worldwide, Inc." },
  { symbol: "CDNS", name: "Cadence Design Systems, Inc." },
  { symbol: "CZR", name: "Caesars Entertainment, Inc." },
  { symbol: "CPT", name: "Camden Property Trust" },
  { symbol: "CPB", name: "Campbell Soup Company" },
  { symbol: "COF", name: "Capital One Financial Corporation" },
  { symbol: "CAH", name: "Cardinal Health, Inc." },
  { symbol: "KMX", name: "CarMax, Inc." },
  { symbol: "CCL", name: "Carnival Corporation & plc" },
  { symbol: "CARR", name: "Carrier Global Corporation" },
  { symbol: "CTLT", name: "Catalent, Inc." },
  { symbol: "CAT", name: "Caterpillar Inc." },
  { symbol: "CBOE", name: "Cboe Global Markets, Inc." },
  { symbol: "CBRE", name: "CBRE Group, Inc." },
  { symbol: "CDW", name: "CDW Corporation" },
  { symbol: "CE", name: "Celanese Corporation" },
  { symbol: "COR", name: "Cencora, Inc." },
  { symbol: "CNC", name: "Centene Corporation" },
  { symbol: "CNP", name: "CenterPoint Energy, Inc." },
  { symbol: "CF", name: "CF Industries Holdings, Inc." },
  { symbol: "CRL", name: "Charles River Laboratories International, Inc." },
  { symbol: "SCHW", name: "The Charles Schwab Corporation" },
  { symbol: "CHTR", name: "Charter Communications, Inc." },
  { symbol: "CVX", name: "Chevron Corporation" },
  { symbol: "CMG", name: "Chipotle Mexican Grill, Inc." },
  { symbol: "CB", name: "Chubb Limited" },
  { symbol: "CHD", name: "Church & Dwight Co., Inc." },
  { symbol: "CI", name: "Cigna Corporation" },
  { symbol: "CINF", name: "Cincinnati Financial Corporation" },
  { symbol: "CTAS", name: "Cintas Corporation" },
  { symbol: "CSCO", name: "Cisco Systems, Inc." },
  { symbol: "C", name: "Citigroup Inc." },
  { symbol: "CFG", name: "Citizens Financial Group, Inc." },
  { symbol: "CLX", name: "The Clorox Company" },
  { symbol: "CME", name: "CME Group Inc." },
  { symbol: "CMS", name: "CMS Energy Corporation" },
  { symbol: "COIN", name: "Coinbase Global, Inc." }, // Added COIN
  { symbol: "KO", name: "The Coca-Cola Company" },
  { symbol: "CTSH", name: "Cognizant Technology Solutions Corporation" },
  { symbol: "CL", name: "Colgate-Palmolive Company" },
  { symbol: "CMCSA", name: "Comcast Corporation" },
  { symbol: "CMA", name: "Comerica Incorporated" },
  { symbol: "CAG", name: "Conagra Brands, Inc." },
  { symbol: "COP", name: "ConocoPhillips" },
  { symbol: "ED", name: "Consolidated Edison, Inc." },
  { symbol: "STZ", name: "Constellation Brands, Inc." },
  { symbol: "CEG", name: "Constellation Energy Corporation" },
  { symbol: "COO", name: "The Cooper Companies, Inc." },
  { symbol: "CPRT", name: "Copart, Inc." },
  { symbol: "GLW", name: "Corning Incorporated" },
  { symbol: "CPAY", name: "Corpay, Inc." },
  { symbol: "CTVA", name: "Corteva, Inc." },
  { symbol: "CSGP", name: "CoStar Group, Inc." },
  { symbol: "COST", name: "Costco Wholesale Corporation" },
  { symbol: "COTY", name: "Coty Inc." },
  { symbol: "CCI", name: "Crown Castle Inc." },
  { symbol: "CSX", name: "CSX Corporation" },
  { symbol: "CMI", name: "Cummins Inc." },
  { symbol: "CVS", name: "CVS Health Corporation" },
  { symbol: "DHR", name: "Danaher Corporation" },
  { symbol: "DRI", name: "Darden Restaurants, Inc." },
  { symbol: "DVA", name: "DaVita Inc." },
  { symbol: "DAY", name: "Dayforce Inc." },
  { symbol: "DECK", name: "Deckers Outdoor Corporation" },
  { symbol: "DE", name: "Deere & Company" },
  { symbol: "DAL", name: "Delta Air Lines, Inc." },
  { symbol: "XRAY", name: "Dentsply Sirona Inc." },
  { symbol: "DVN", name: "Devon Energy Corporation" },
  { symbol: "DXCM", name: "DexCom, Inc." },
  { symbol: "FANG", name: "Diamondback Energy, Inc." },
  { symbol: "DLR", name: "Digital Realty Trust, Inc." },
  { symbol: "DFS", name: "Discover Financial Services" },
  { symbol: "DG", name: "Dollar General Corporation" },
  { symbol: "DLTR", name: "Dollar Tree, Inc." },
  { symbol: "D", name: "Dominion Energy, Inc." },
  { symbol: "DPZ", name: "Domino's Pizza, Inc." },
  { symbol: "DOV", name: "Dover Corporation" },
  { symbol: "DOW", name: "Dow Inc." },
  { symbol: "DHI", name: "D.R. Horton, Inc." },
  { symbol: "DTE", name: "DTE Energy Company" },
  { symbol: "DUK", name: "Duke Energy Corporation" },
  { symbol: "DD", name: "DuPont de Nemours, Inc." },
  { symbol: "EMN", name: "Eastman Chemical Company" },
  { symbol: "ETN", name: "Eaton Corporation plc" },
  { symbol: "EBAY", name: "eBay Inc." },
  { symbol: "ECL", name: "Ecolab Inc." },
  { symbol: "EIX", name: "Edison International" },
  { symbol: "EW", name: "Edwards Lifesciences Corporation" },
  { symbol: "EA", name: "Electronic Arts Inc." },
  { symbol: "ELV", name: "Elevance Health, Inc." },
  { symbol: "EMR", name: "Emerson Electric Co." },
  { symbol: "ENPH", name: "Enphase Energy, Inc." },
  { symbol: "ETR", name: "Entergy Corporation" },
  { symbol: "EOG", name: "EOG Resources, Inc." },
  { symbol: "EPAM", name: "EPAM Systems, Inc." },
  { symbol: "EQT", name: "EQT Corporation" },
  { symbol: "EFX", name: "Equifax Inc." },
  { symbol: "EQIX", name: "Equinix, Inc." },
  { symbol: "EQR", name: "Equity Residential" },
  { symbol: "ESS", name: "Essex Property Trust, Inc." },
  { symbol: "EL", name: "The Estée Lauder Companies Inc." },
  { symbol: "ETSY", name: "Etsy, Inc." },
  { symbol: "EG", name: "Everest Group, Ltd." },
  { symbol: "EVRG", name: "Evergy, Inc." },
  { symbol: "ES", name: "Eversource Energy" },
  { symbol: "EXC", name: "Exelon Corporation" },
  { symbol: "EXPE", name: "Expedia Group, Inc." },
  { symbol: "EXPD", name: "Expeditors International of Washington, Inc." },
  { symbol: "EXR", name: "Extra Space Storage Inc." },
  { symbol: "XOM", name: "Exxon Mobil Corporation" },
  { symbol: "FFIV", name: "F5, Inc." },
  { symbol: "FDS", name: "FactSet Research Systems Inc." },
  { symbol: "FICO", name: "Fair Isaac Corporation" },
  { symbol: "FAST", name: "Fastenal Company" },
  { symbol: "FRT", name: "Federal Realty Investment Trust" },
  { symbol: "FDX", name: "FedEx Corporation" },
  { symbol: "FIS", name: "Fidelity National Information Services, Inc." },
  { symbol: "FITB", name: "Fifth Third Bancorp" },
  { symbol: "FSLR", name: "First Solar, Inc." },
  { symbol: "FE", name: "FirstEnergy Corp." },
  { symbol: "FI", name: "Fiserv, Inc." },
  { symbol: "FMC", name: "FMC Corporation" },
  { symbol: "F", name: "Ford Motor Company" },
  { symbol: "FTNT", name: "Fortinet, Inc." },
  { symbol: "FTV", name: "Fortive Corporation" },
  { symbol: "FOXA", name: "Fox Corporation (Class A)" },
  { symbol: "FOX", name: "Fox Corporation (Class B)" },
  { symbol: "BEN", name: "Franklin Resources, Inc." },
  { symbol: "FCX", name: "Freeport-McMoRan Inc." },
  { symbol: "GRMN", name: "Garmin Ltd." },
  { symbol: "IT", name: "Gartner, Inc." },
  { symbol: "GE", name: "GE Aerospace" },
  { symbol: "GEHC", name: "GE HealthCare Technologies Inc." },
  { symbol: "GEV", name: "GE Vernova Inc." },
  { symbol: "GEN", name: "Gen Digital Inc." },
  { symbol: "GNRC", name: "Generac Holdings Inc." },
  { symbol: "GD", name: "General Dynamics Corporation" },
  { symbol: "GIS", name: "General Mills, Inc." },
  { symbol: "GM", name: "General Motors Company" },
  { symbol: "GPC", name: "Genuine Parts Company" },
  { symbol: "GILD", name: "Gilead Sciences, Inc." },
  { symbol: "GPN", name: "Global Payments Inc." },
  { symbol: "GL", name: "Globe Life Inc." },
  { symbol: "GDDY", name: "GoDaddy Inc." },
  { symbol: "GS", name: "The Goldman Sachs Group, Inc." },
  { symbol: "HAL", name: "Halliburton Company" },
  { symbol: "HIG", name: "The Hartford Financial Services Group, Inc." },
  { symbol: "HAS", name: "Hasbro, Inc." },
  { symbol: "HCA", name: "HCA Healthcare, Inc." },
  { symbol: "HD", name: "The Home Depot, Inc." },
  { symbol: "HES", name: "Hess Corporation" },
  { symbol: "HPE", name: "Hewlett Packard Enterprise Company" },
  { symbol: "HLT", name: "Hilton Worldwide Holdings Inc." },
  { symbol: "HOLX", name: "Hologic, Inc." },
  { symbol: "HON", name: "Honeywell International Inc." },
  { symbol: "HRL", name: "Hormel Foods Corporation" },
  { symbol: "HST", name: "Host Hotels & Resorts, Inc." },
  { symbol: "HWM", name: "Howmet Aerospace Inc." },
  { symbol: "HPQ", name: "HP Inc." },
  { symbol: "HUBB", name: "Hubbell Inc." },
  { symbol: "HUM", name: "Humana Inc." },
  { symbol: "HBAN", name: "Huntington Bancshares Incorporated" },
  { symbol: "HII", name: "Huntington Ingalls Industries, Inc." },
  { symbol: "IBM", name: "International Business Machines Corporation" },
  { symbol: "IEX", name: "IDEX Corporation" },
  { symbol: "IDXX", name: "IDEXX Laboratories, Inc." },
  { symbol: "ITW", name: "Illinois Tool Works Inc." },
  { symbol: "INCY", name: "Incyte Corporation" },
  { symbol: "IR", name: "Ingersoll Rand Inc." },
  { symbol: "PODD", name: "Insulet Corporation" },
  { symbol: "INTC", name: "Intel Corporation" },
  { symbol: "ICE", name: "Intercontinental Exchange, Inc." },
  { symbol: "IFF", name: "International Flavors & Fragrances Inc." },
  { symbol: "IP", name: "International Paper Company" },
  { symbol: "IPG", name: "The Interpublic Group of Companies, Inc." },
  { symbol: "INTU", name: "Intuit Inc." },
  { symbol: "ISRG", name: "Intuitive Surgical, Inc." },
  { symbol: "IVZ", name: "Invesco Ltd." },
  { symbol: "INVH", name: "Invitation Homes Inc." },
  { symbol: "IQV", name: "IQVIA Holdings Inc." },
  { symbol: "IRM", name: "Iron Mountain Incorporated" },
  { symbol: "JBHT", name: "J.B. Hunt Transport Services, Inc." },
  { symbol: "JBL", name: "Jabil Inc." },
  { symbol: "JKHY", name: "Jack Henry & Associates, Inc." },
  { symbol: "J", name: "Jacobs Solutions Inc." },
  { symbol: "JNJ", name: "Johnson & Johnson" },
  { symbol: "JCI", name: "Johnson Controls International plc" },
  { symbol: "JPM", name: "JPMorgan Chase & Co." },
  { symbol: "JNPR", name: "Juniper Networks, Inc." },
  { symbol: "K", name: "Kellanova" },
  { symbol: "KVUE", name: "Kenvue Inc." },
  { symbol: "KDP", name: "Keurig Dr Pepper Inc." },
  { symbol: "KEY", name: "KeyCorp" },
  { symbol: "KEYS", name: "Keysight Technologies, Inc." },
  { symbol: "KMB", name: "Kimberly-Clark Corporation" },
  { symbol: "KIM", name: "Kimco Realty Corporation" },
  { symbol: "KMI", name: "Kinder Morgan, Inc." },
  { symbol: "KLAC", name: "KLA Corporation" },
  { symbol: "KHC", name: "The Kraft Heinz Company" },
  { symbol: "KR", name: "The Kroger Co." },
  { symbol: "LHX", name: "L3Harris Technologies, Inc." },
  { symbol: "LH", name: "Labcorp Holdings Inc." },
  { symbol: "LRCX", name: "Lam Research Corporation" },
  { symbol: "LW", name: "Lamb Weston Holdings, Inc." },
  { symbol: "LVS", name: "Las Vegas Sands Corp." },
  { symbol: "LDOS", name: "Leidos Holdings, Inc." },
  { symbol: "LEN", name: "Lennar Corporation" },
  { symbol: "LLY", name: "Eli Lilly and Company" },
  { symbol: "LNC", name: "Lincoln National Corporation" },
  { symbol: "LIN", name: "Linde plc" },
  { symbol: "LYV", name: "Live Nation Entertainment, Inc." },
  { symbol: "LKQ", name: "LKQ Corporation" },
  { symbol: "LMT", name: "Lockheed Martin Corporation" },
  { symbol: "L", name: "Loews Corporation" },
  { symbol: "LOW", name: "Lowe's Companies, Inc." },
  { symbol: "LULU", name: "Lululemon Athletica Inc." },
  { symbol: "LYB", name: "LyondellBasell Industries N.V." },
  { symbol: "MTB", name: "M&T Bank Corporation" },
  { symbol: "MRO", name: "Marathon Oil Corporation" },
  { symbol: "MPC", name: "Marathon Petroleum Corporation" },
  { symbol: "MKTX", name: "MarketAxess Holdings Inc." },
  { symbol: "MAR", name: "Marriott International, Inc." },
  { symbol: "MMC", name: "Marsh & McLennan Companies, Inc." },
  { symbol: "MLM", name: "Martin Marietta Materials, Inc." },
  { symbol: "MAS", name: "Masco Corporation" },
  { symbol: "MA", name: "Mastercard Incorporated" },
  { symbol: "MTCH", name: "Match Group, Inc." },
  { symbol: "MKC", name: "McCormick & Company, Incorporated" },
  { symbol: "MCD", name: "McDonald's Corporation" },
  { symbol: "MCK", name: "McKesson Corporation" },
  { symbol: "MDT", name: "Medtronic plc" },
  { symbol: "MRK", name: "Merck & Co., Inc." },
  { symbol: "META", name: "Meta Platforms, Inc." },
  { symbol: "MET", name: "MetLife, Inc." },
  { symbol: "MTD", name: "Mettler-Toledo International Inc." },
  { symbol: "MGM", name: "MGM Resorts International" },
  { symbol: "MCHP", name: "Microchip Technology Incorporated" },
  { symbol: "MU", name: "Micron Technology, Inc." },
  { symbol: "MSFT", name: "Microsoft Corporation" },
  { symbol: "MAA", name: "Mid-America Apartment Communities, Inc." },
  { symbol: "MRNA", name: "Moderna, Inc." },
  { symbol: "MHK", name: "Mohawk Industries, Inc." },
  { symbol: "MOH", name: "Molina Healthcare, Inc." },
  { symbol: "TAP", name: "Molson Coors Beverage Company" },
  { symbol: "MDLZ", name: "Mondelez International, Inc." },
  { symbol: "MPWR", name: "Monolithic Power Systems, Inc." },
  { symbol: "MNST", name: "Monster Beverage Corporation" },
  { symbol: "MCO", name: "Moody's Corporation" },
  { symbol: "MS", name: "Morgan Stanley" },
  { symbol: "MOS", name: "The Mosaic Company" },
  { symbol: "MSI", name: "Motorola Solutions, Inc." },
  { symbol: "MSCI", name: "MSCI Inc." },
  { symbol: "NDAQ", name: "Nasdaq, Inc." },
  { symbol: "NTAP", name: "NetApp, Inc." },
  { symbol: "NFLX", name: "Netflix, Inc." },
  { symbol: "NEM", name: "Newmont Corporation" },
  { symbol: "NWSA", name: "News Corporation (Class A)" },
  { symbol: "NWS", name: "News Corporation (Class B)" },
  { symbol: "NEE", name: "NextEra Energy, Inc." },
  { symbol: "NKE", name: "NIKE, Inc." },
  { symbol: "NI", name: "NiSource Inc." },
  { symbol: "NDSN", name: "Nordson Corporation" },
  { symbol: "NSC", name: "Norfolk Southern Corporation" },
  { symbol: "NTRS", name: "Northern Trust Corporation" },
  { symbol: "NOC", name: "Northrop Grumman Corporation" },
  { symbol: "NCLH", name: "Norwegian Cruise Line Holdings Ltd." },
  { symbol: "NRG", name: "NRG Energy, Inc." },
  { symbol: "NUE", name: "Nucor Corporation" },
  { symbol: "NVDA", name: "NVIDIA Corporation" },
  { symbol: "NVR", name: "NVR, Inc." },
  { symbol: "NXPI", name: "NXP Semiconductors N.V." },
  { symbol: "ORLY", name: "O'Reilly Automotive, Inc." },
  { symbol: "OXY", name: "Occidental Petroleum Corporation" },
  { symbol: "ODFL", name: "Old Dominion Freight Line, Inc." },
  { symbol: "OMC", name: "Omnicom Group Inc." },
  { symbol: "ON", name: "ON Semiconductor Corporation" },
  { symbol: "OKE", name: "ONEOK, Inc." },
  { symbol: "ORCL", name: "Oracle Corporation" },
  { symbol: "OTIS", name: "Otis Worldwide Corporation" },
  { symbol: "PCAR", name: "PACCAR Inc." },
  { symbol: "PKG", name: "Packaging Corporation of America" },
  { symbol: "PANW", name: "Palo Alto Networks, Inc." },
  { symbol: "PARA", name: "Paramount Global" },
  { symbol: "PH", name: "Parker-Hannifin Corporation" },
  { symbol: "PAYX", name: "Paychex, Inc." },
  { symbol: "PAYC", name: "Paycom Software, Inc." },
  { symbol: "PYPL", name: "PayPal Holdings, Inc." },
  { symbol: "PNR", name: "Pentair plc" },
  { symbol: "PEP", name: "PepsiCo, Inc." },
  { symbol: "PFE", name: "Pfizer Inc." },
  { symbol: "PCG", name: "PG&E Corporation" },
  { symbol: "PM", name: "Philip Morris International Inc." },
  { symbol: "PSX", name: "Phillips 66" },
  { symbol: "PNW", name: "Pinnacle West Capital Corporation" },
  { symbol: "PNC", name: "The PNC Financial Services Group, Inc." },
  { symbol: "POOL", name: "Pool Corporation" },
  { symbol: "PPG", name: "PPG Industries, Inc." },
  { symbol: "PPL", name: "PPL Corporation" },
  { symbol: "PFG", name: "Principal Financial Group, Inc." },
  { symbol: "PG", name: "The Procter & Gamble Company" },
  { symbol: "PGR", name: "The Progressive Corporation" },
  { symbol: "PLD", name: "Prologis, Inc." },
  { symbol: "PRU", name: "Prudential Financial, Inc." },
  { symbol: "PEG", name: "Public Service Enterprise Group Incorporated" },
  { symbol: "PTC", name: "PTC Inc." },
  { symbol: "PSA", name: "Public Storage" },
  { symbol: "PHM", name: "PulteGroup, Inc." },
  { symbol: "QRVO", name: "Qorvo, Inc." },
  { symbol: "PWR", name: "Quanta Services, Inc." },
  { symbol: "QCOM", name: "QUALCOMM Incorporated" },
  { symbol: "DGX", name: "Quest Diagnostics Incorporated" },
  { symbol: "RL", name: "Ralph Lauren Corporation" },
  { symbol: "RJF", name: "Raymond James Financial, Inc." },
  { symbol: "RTX", name: "RTX Corporation" },
  { symbol: "O", name: "Realty Income Corporation" },
  { symbol: "REG", name: "Regency Centers Corporation" },
  { symbol: "REGN", name: "Regeneron Pharmaceuticals, Inc." },
  { symbol: "RF", name: "Regions Financial Corporation" },
  { symbol: "RSG", name: "Republic Services, Inc." },
  { symbol: "RMD", name: "ResMed Inc." },
  { symbol: "RVTY", name: "Revvity, Inc." },
  { symbol: "RHI", name: "Robert Half Inc." },
  { symbol: "ROK", name: "Rockwell Automation, Inc." },
  { symbol: "ROL", name: "Rollins, Inc." },
  { symbol: "ROP", name: "Roper Technologies, Inc." },
  { symbol: "ROST", name: "Ross Stores, Inc." },
  { symbol: "RCL", name: "Royal Caribbean Cruises Ltd." },
  { symbol: "SPGI", name: "S&P Global Inc." },
  { symbol: "CRM", name: "Salesforce, Inc." },
  { symbol: "SBAC", name: "SBA Communications Corporation" },
  { symbol: "SLB", name: "Schlumberger Limited" },
  { symbol: "STX", name: "Seagate Technology Holdings plc" },
  { symbol: "SRE", name: "Sempra" },
  { symbol: "NOW", name: "ServiceNow, Inc." },
  { symbol: "SHW", name: "The Sherwin-Williams Company" },
  { symbol: "SPG", name: "Simon Property Group, Inc." },
  { symbol: "SWKS", name: "Skyworks Solutions, Inc." },
  { symbol: "SJM", name: "The J. M. Smucker Company" },
  { symbol: "SMCI", name: "Super Micro Computer, Inc." },
  { symbol: "SNA", name: "Snap-on Incorporated" },
  { symbol: "SOLV", name: "Solventum Corporation" },
  { symbol: "SO", name: "The Southern Company" },
  { symbol: "LUV", name: "Southwest Airlines Co." },
  { symbol: "SWK", name: "Stanley Black & Decker, Inc." },
  { symbol: "SBUX", name: "Starbucks Corporation" },
  { symbol: "STT", name: "State Street Corporation" },
  { symbol: "STLD", name: "Steel Dynamics, Inc." },
  { symbol: "STE", name: "STERIS plc" },
  { symbol: "SYK", name: "Stryker Corporation" },
  { symbol: "SYF", name: "Synchrony Financial" },
  { symbol: "SNPS", name: "Synopsys, Inc." },
  { symbol: "SYY", name: "Sysco Corporation" },
  { symbol: "TMUS", name: "T-Mobile US, Inc." },
  { symbol: "TROW", name: "T. Rowe Price Group, Inc." },
  { symbol: "TTWO", name: "Take-Two Interactive Software, Inc." },
  { symbol: "TPR", name: "Tapestry, Inc." },
  { symbol: "TRGP", name: "Targa Resources Corp." },
  { symbol: "TGT", name: "Target Corporation" },
  { symbol: "TEL", name: "TE Connectivity Ltd." },
  { symbol: "TDY", name: "Teledyne Technologies Incorporated" },
  { symbol: "TFX", name: "Teleflex Incorporated" },
  { symbol: "TER", name: "Teradyne, Inc." },
  { symbol: "TSLA", name: "Tesla, Inc." },
  { symbol: "TXN", name: "Texas Instruments Incorporated" },
  { symbol: "TXT", name: "Textron Inc." },
  { symbol: "TMO", name: "Thermo Fisher Scientific Inc." },
  { symbol: "TJX", name: "The TJX Companies, Inc." },
  { symbol: "TSCO", name: "Tractor Supply Company" },
  { symbol: "TT", name: "Trane Technologies plc" },
  { symbol: "TDG", name: "TransDigm Group Incorporated" },
  { symbol: "TRV", name: "The Travelers Companies, Inc." },
  { symbol: "TRMB", name: "Trimble Inc." },
  { symbol: "TFC", name: "Truist Financial Corporation" },
  { symbol: "TYL", name: "Tyler Technologies, Inc." },
  { symbol: "TSN", name: "Tyson Foods, Inc." },
  { symbol: "USB", name: "U.S. Bancorp" },
  { symbol: "UBER", name: "Uber Technologies, Inc." },
  { symbol: "UDR", name: "UDR, Inc." },
  { symbol: "ULTA", name: "Ulta Beauty, Inc." },
  { symbol: "UNP", name: "Union Pacific Corporation" },
  { symbol: "UAL", name: "United Airlines Holdings, Inc." },
  { symbol: "UPS", name: "United Parcel Service, Inc." },
  { symbol: "URI", name: "United Rentals, Inc." },
  { symbol: "UNH", name: "UnitedHealth Group Incorporated" },
  { symbol: "UHS", name: "Universal Health Services, Inc." },
  { symbol: "VLO", name: "Valero Energy Corporation" },
  { symbol: "VTR", name: "Ventas, Inc." },
  { symbol: "VLTO", name: "Veralto Corporation" },
  { symbol: "VRSN", name: "VeriSign, Inc." },
  { symbol: "VRSK", name: "Verisk Analytics, Inc." },
  { symbol: "VZ", name: "Verizon Communications Inc." },
  { symbol: "VRTX", name: "Vertex Pharmaceuticals Incorporated" },
  { symbol: "VTRS", name: "Viatris Inc." },
  { symbol: "VICI", name: "VICI Properties Inc." },
  { symbol: "V", name: "Visa Inc." },
  { symbol: "VIV", name: "Vistra Corp." },
  { symbol: "VMC", name: "Vulcan Materials Company" },
  { symbol: "WRB", name: "W. R. Berkley Corporation" },
  { symbol: "WAB", name: "Westinghouse Air Brake Technologies Corporation" },
  { symbol: "WBA", name: "Walgreens Boots Alliance, Inc." },
  { symbol: "WMT", name: "Walmart Inc." },
  { symbol: "DIS", name: "The Walt Disney Company" },
  { symbol: "WBD", name: "Warner Bros. Discovery, Inc." },
  { symbol: "WM", name: "Waste Management, Inc." },
  { symbol: "WAT", name: "Waters Corporation" },
  { symbol: "WEC", name: "WEC Energy Group, Inc." },
  { symbol: "WFC", name: "Wells Fargo & Company" },
  { symbol: "WELL", name: "Welltower Inc." },
  { symbol: "WST", name: "West Pharmaceutical Services, Inc." },
  { symbol: "WDC", name: "Western Digital Corporation" },
  { symbol: "WRK", name: "WestRock Company" },
  { symbol: "WY", name: "Weyerhaeuser Company" },
  { symbol: "WMB", name: "The Williams Companies, Inc." },
  { symbol: "WTW", name: "Willis Towers Watson Public Limited Company" },
  { symbol: "GWW", name: "W.W. Grainger, Inc." },
  { symbol: "WYNN", name: "Wynn Resorts, Limited" },
  { symbol: "XEL", name: "Xcel Energy Inc." },
  { symbol: "XYL", name: "Xylem Inc." },
  { symbol: "YUM", name: "Yum! Brands, Inc." },
  { symbol: "ZBRA", name: "Zebra Technologies Corporation" },
  { symbol: "ZBH", name: "Zimmer Biomet Holdings, Inc." },
  { symbol: "ZTS", name: "Zoetis Inc." }
];

// Extract just the symbols for backward compatibility
const SP500_SYMBOLS = SP500_COMPANIES.map(company => company.symbol);

// Function to get rebalance dates (unchanged)
function getRebalanceDates() {
  const today = new Date();
  today.setHours(0, 0, 0, 0);
  
  function getThirdFriday(year, month) {
    const date = new Date(year, month, 1);
    const firstDay = date.getDay();
    const firstFriday = firstDay <= 5 ? 5 - firstDay : 12 - firstDay;
    const thirdFriday = firstFriday + 14;
    return new Date(year, month, thirdFriday);
  }
  
  const rebalanceMonths = [2, 5, 8, 11]; // March, June, September, December
  const dates = [];
  
  // Get current year rebalance dates
  const currentYear = today.getFullYear();
  for (const month of rebalanceMonths) {
    const date = getThirdFriday(currentYear, month);
    dates.push(date);
  }
  
  // Also get first rebalance date of next year
  dates.push(getThirdFriday(currentYear + 1, 2));
  
  // Handle June 2025 exception
  const june2025 = dates.find(d => d.getFullYear() === 2025 && d.getMonth() === 5);
  if (june2025) {
    june2025.setDate(6); // June 6, 2025
  }
  
  // Find last and next rebalance dates
  let lastRebalance = null;
  let nextRebalance = null;
  
  for (const date of dates) {
    if (date <= today) {
      lastRebalance = date;
    } else if (!nextRebalance) {
      nextRebalance = date;
    }
  }
  
  // If no last rebalance found in current year, get December of previous year
  if (!lastRebalance) {
    lastRebalance = getThirdFriday(currentYear - 1, 11);
  }
  
  return { lastRebalance, nextRebalance };
}

module.exports = { SP500_SYMBOLS, SP500_COMPANIES, getRebalanceDates };
